# Generated by Django 4.2.4 on 2023-09-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdownvoted',
            old_name='post',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlove',
            old_name='post',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentupvoted',
            old_name='post',
            new_name='comment',
        ),
    ]
