# Generated by Django 4.2.4 on 2023-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_post_commentdownvoted_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_messages_count',
            field=models.IntegerField(default=0),
        ),
    ]
