# Generated by Django 4.2.4 on 2023-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_unread_messages_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_notifications_count',
            field=models.IntegerField(default=0),
        ),
    ]
