# Generated by Django 4.2.5 on 2023-10-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_unread_notifications_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
