# Generated by Django 4.2.6 on 2023-10-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_comment_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='followers',
        ),
    ]
