# Generated by Django 4.2.6 on 2023-10-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures/'),
        ),
    ]
